# Generated by Django 3.1.1 on 2020-10-27 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20201027_0141'),
    ]

    operations = [
        migrations.AddField(
            model_name='art',
            name='approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='video',
            name='video',
            field=models.FileField(upload_to='static/images/'),
        ),
    ]
