# Generated by Django 3.1.1 on 2020-10-27 20:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_auto_20201028_0028'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Video',
        ),
    ]
